[package]
name = "service"
version = "0.1.0"
authors = ["Christopher Altona <christopher.altona@adp.com>"]
edition = "2018"

[dependencies]
rocket = "0.4.0"
rocket_contrib = "0.4.0"
serde = "1.0.82"
serde_derive = "1.0.82"
lazy_static = "1.2.0"